### ISSUE TITLE
cant join server

### ISSUE THREAD

**Issue by thewanderingtraderm** [Protonull/BasicMinestomServer#2]
it gets stuck on joining world

**Comment by Protonull** [comment]
Heard about [something like this](https://discord.com/channels/706185253441634317/706186227493109860/1234921662177349763), so I've pulled the latest commit from Minestom. See if that helps.

**Comment by thewanderingtraderm** [comment]
it still doesn't connect

**Comment by Protonull** [comment]
Would you mind showing your setup? Do you have links to the extensions you're using? And are there any warnings or errors in the console?

**Comment by thewanderingtraderm** [comment]
i think its because of an instance not being included

**Comment by Protonull** [comment]
Keep in mind that BasicMinestomServer's mandate is simply to provide a runnable jar; it does not provide any custom behaviour whatsoever. Creating an instance and spawning players into that instance is considered custom behaviour. You'd need to create an extension that reimplements what the Minestom wiki explains in its ["Your first server"](https://wiki.minestom.net/setup/your-first-server) page, sans the `MinecraftServer.init()` and the `minecraftServer.start("0.0.0.0", 25565)` since BasicMinestomServer does that for you.
